import type { Metadata, Viewport } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Header from "./_component/header";
import Provider from "./_component/Provider";
import ThemeButton from "./_component/ThemeButton";

const noto = Noto_Sans_KR({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "프론트엔드 개발자 황서연의 포트폴리오",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
  minimumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Provider>
          <Header />
          <div className="flex justify-center">
            <div className="w-full h-full pt-[63px] max-w-[70rem]">
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
